### ISSUE TITLE
Version 1.3.2 is missing fix for issue 207

### ISSUE THREAD

**Issue by mro** [piccolo2d/piccolo2d.java#254]
Originally reported on Google Code with ID 254
```
The fix for issue 207 was applied to branches/release-1.3.1 and the 1.3.2 release was
cut from branches/release-1.3.
```

Reported by `heuermh` on 2013-12-05 16:49:23

**Comment by heuermh** [comment]
I don't plan on releasing anything other than from master, in other words the 3.x series of releases.

**Comment by heuermh** [comment]
Closing as WontFix
