### ISSUE TITLE
Update project metadata from Google Code to Github transition

### ISSUE THREAD

**Issue by heuermh** [piccolo2d/piccolo2d.java#267]

**Comment by mro** [comment]
Hi Michael,
not sure what you mean with metadata - but the downloads page has a lot of links to zip files which I'd rather not put into the website repo. Somehow feels wrong. But I also don't know where else to put them. What do you think?

P.S.: some broken links: https://validator.w3.org/checklink?uri=http%3A%2F%2Fpiccolo2d.mro.name%2Fdownload.html&hide_type=all&check=Check

**Comment by heuermh** [comment]
Sorry for not being more clear -- for this issue I meant the project metadata in the pom files, like the ```<scm>``` element.

**Comment by heuermh** [comment]
Oops, I created a pull request for this
https://github.com/heuermh/piccolo2d.java/pull/1
but apparently that wasn't a fork of this repository!  Will try again.
