### ISSUE TITLE
PFixedWidthStroke wrong

### ISSUE THREAD

**Issue by fjutlj** [piccolo2d/piccolo2d.java#270]
When I use PFixedWidthStroke to fix the line width,then zoom in the line. The line width will change if  the mouse click on the canvas, sometime thick ,sometime thin.

**Comment by heuermh** [comment]
Note that rendering may be different when interacting with the canvas, unless all render quality settings are the same, e.g.
```java
canvas.setDefaultRenderQuality(PPaintContext.HIGH_QUALITY_RENDERING);
canvas.setAnimatingRenderQuality(PPaintContext.HIGH_QUALITY_RENDERING);
canvas.setInteractingRenderQuality(PPaintContext.HIGH_QUALITY_RENDERING);
```
The defaults are here https://github.com/piccolo2d/piccolo2d.java/blob/master/core/src/main/java/org/piccolo2d/PCanvas.java#L149

**Comment by heuermh** [comment]
Closing as not an issue.
