### ISSUE TITLE
jsweet port to JS

### ISSUE THREAD

**Issue by zzj1213** [piccolo2d/piccolo2d.java#272]
Is it possible to use http://www.jsweet.org/ to port piccolo2d to pure HTML5 JS ?  JSweet has example to port Java Applet to JS: https://porter.io/github.com/cincheo/applet-migration-example

**Comment by heuermh** [comment]
Hello @zzj1213!

There is a port/adaptation of Piccolo2D to javascript at http://allain.github.io/piccolo2d.js.  If you'd like to try jsweet and it does something reasonable, please create a pull request here.
